#!/bin/bash
# start_service.sh — The actual job script (runs on the COMPUTE node).
#
# This script is APPENDED to boilerplate generated by the session runner.
# By the time this code runs, the following are already done:
#   - inputs.sh is sourced  (fractal_* variables are exported)
#   - service_port is set   (via `pw agent open-port`)
#   - SESSION_PORT file written
#   - HOSTNAME file written
#   - cleanup() trap registered (kills process group on exit)
#   - job.started touched
#
# Responsibilities:
#   1. Start the mandelbrot computation in the background
#   2. Start the Flask web server in the foreground on ${service_port}
#      (the session tunnel connects to this port)

set -x

DEMO_DIR="${HOME}/cuda-checkpoint-demo"

# ── Shared data directory ─────────────────────────────────────────────────────
mkdir -p "${DEMO_DIR}/shared"

# ── 1. Start fractal computation in background ────────────────────────────────
# The binary was compiled by controller.sh with the form parameters baked in.
# We run it detached so this script stays alive as the Flask process.
echo "Starting mandelbrot computation..."
"${DEMO_DIR}/01_fractal/mandelbrot" \
    > "${DEMO_DIR}/shared/mandelbrot.log" 2>&1 &
FRACTAL_PID=$!
echo "Fractal PID: ${FRACTAL_PID}"

# ── 2. Start Flask web server (foreground — session lives while Flask runs) ───
echo "Starting Flask dashboard on port ${service_port}..."
cd "${DEMO_DIR}/02_webserver"
PORT="${service_port}" python3 server.py
